import imgQueretaro from "@/assets/img/BlogGeneric/find-queretaro1.png";
import imgMazatlan from "@/assets/img/BlogGeneric/knows-mazatlan1.png";
import imgMiami from "@/assets/img/BlogGeneric/knows-miami-beach1.png";
import imgVallarta from "@/assets/img/BlogGeneric/knows-puerto-vallarta1.png";
import imgTampico from "@/assets/img/BlogGeneric/knows-tampico1.png";
import imgCancun from "@/assets/img/BlogGeneric/knows-cancun1.png";
import imgCayo from "@/assets/img/BlogGeneric/knows-cayo-cuba1.png";
//IXTAPA IMAGE.JPG FAILED TO UPLOAD
import imgIxtapa from "@/assets/img/BlogGeneric/knows-ixtapa1.jpg";
import imgMerida from "@/assets/img/BlogGeneric/knows-merida1.png";
import imgMelia from "@/assets/img/BlogGeneric/knows-melia1.png";
import imgAcapulco from "@/assets/img/BlogGeneric/discover-acapulco1.png";
import imgDiscoverCancun from "@/assets/img/BlogGeneric/discover-cancun1.png";
import imgRiviera from "@/assets/img/BlogGeneric/discover-riviera-maya1.png";
import imgMexico from "@/assets/img/BlogGeneric/discover-mexico1.png";
import imgNuevoVallarta from "@/assets/img/BlogGeneric/discover-nuevo-vallarta1.png";
import imgDisney from "@/assets/img/BlogGeneric/discover-disney1.png";
import imgCuernavaca from "@/assets/img/BlogGeneric/discover-cuernavaca1.png";
import imgGuayabitos from "@/assets/img/BlogGeneric/discover-guayabitos1.png";
import imgHabana from "@/assets/img/BlogGeneric/discover-habana1.jpg";
import imgTolantongo from "@/assets/img/BlogGeneric/discover-grutas-de-tolantongo.jpg";
import imgCabos from "@/assets/img/BlogGeneric/discover-los-cabos-san-lucas.jpg";
import imgMahahual from "@/assets/img/BlogGeneric/discover-mahahual.jpg";
import imgNewYork from "@/assets/img/BlogGeneric/discover-new-york.jpg";
import imgRiuCancun from "@/assets/img/BlogGeneric/discover-riu-cancun.jpg";
import imgExtenAkumal from "@/assets/img/BlogGeneric/exten-discover-akumal1.png";
import imgExtendChihuahua from "@/assets/img/BlogGeneric/exten-discover-chihuahua1.png";
import imgExtenCampeche from "@/assets/img/BlogGeneric/exten-discovering-campeche1.png";
import imgExtenChetumal from "@/assets/img/BlogGeneric/exten-knows-chetumal1.png";
import imgAllInclusiveNuevoVallarta from "@/assets/img/BlogGeneric/discover-nuevo-vallarta-all-inclusive.jpg";
import imgAllInclusiveAcapulco from "@/assets/img/BlogGeneric/find-best-hotel-acapulco-zona-dorada.jpg";
import imgAllInclusiveCancun from "@/assets/img/BlogGeneric/find-best-hotel-cancun.jpg";
import imgAllInclusiveIxtapa from "@/assets/img/BlogGeneric/find-best-hotel-ixtapa.jpg";
import imgAllInclusiveLasVegas from "@/assets/img/BlogGeneric/find-best-hotel-las-vegas.jpg";
import imgExtenNavidad from "@/assets/img/BlogGeneric/exten-barra-navidad1.png";
import imgExtenChiapas from "@/assets/img/BlogGeneric/exten-chiapas-magic1.png";
import imgAllInclusivePuntaCana from "@/assets/img/BlogGeneric/find-best-hotel-all-inclusive-punta-cana.jpg";
import imgFindHolbox from "@/assets/img/BlogGeneric/find-holbox1.png";
import imgFindPuertoEscondido from "@/assets/img/BlogGeneric/find-puerto-escondido1.png";
import imgFindCancunFamily from "@/assets/img/BlogGeneric/find-cancun-family1.png";
import imgFindPuertoVallarta from "@/assets/img/BlogGeneric/find-puerto-vallarta1.png";
import imgFindVaraderoCuba from "@/assets/img/BlogGeneric/find-varadero-cuba1.png";
import imgExtenBacalar from "@/assets/img/BlogGeneric/exten-bacalar1.png";
import imgExtenGuideCatemaco from "@/assets/img/BlogGeneric/exten-guide-catemaco1.png";
import imgExtenSecretsCancun from "@/assets/img/BlogGeneric/exten-secrets-cancun1.png";
import imgExtenAguascalientes from "@/assets/img/BlogGeneric/exten-aguascalientes1.png";
import imgExtenComeAcapulco from "@/assets/img/BlogGeneric/exten-come-acapulco1.png";
import { Description } from "@mui/icons-material";

export const BlogJsonG = [
  {
    lang: "es",
    name: "FindQueretaro",
    nameEs: "Encuentra cuál es el mejor hotel en Querétaro",
    nameEn: "Find out which is the best hotel in Querétaro",
    descriptionEs:
      "El mejor hotel en Querétaro tiene que ser más que un lugar para descansar; debe ser una experiencia que encapsule la",
    descriptionEn: "The best hotel in Querétaro must be more than just a place to rest; it should be an experience that encapsulates the essence of Mexican hospitality, blending modernity with tradition.",
    codeName: "the-best-hotel-queretaro",
    image: imgQueretaro,
    date: "06/05/2024",
    description: "description",
    type: ["hotel", "other"],
  },
  {
    lang: "es",
    name: "KnowsMazatlan",
    nameEs: "Conoce cuál es el mejor hotel de Mazatlán",
    nameEn: "Discover the best hotel in Mazatlán",
    descriptionEs:
      "Cuando planeamos unas vacaciones en la playa, uno de los destinos más cautivadores de México es sin duda Mazatlán. Sin embargo",
    descriptionEn: "When planning a beach vacation, one of the most captivating destinations in Mexico is undoubtedly Mazatlán. However, with so many lodging options in this wonderful paradise, it's common to wonder.",
    codeName: "the-best-hotel-mazatlan",
    image: imgMazatlan,
    date: "06/05/2024",
    description: "description",
    type: ["beach"],
  },
  {
    lang: "es",
    name: "KnowsMiamiBeach",
    nameEs: "Conoce cuál es el mejor hotel de Miami Beach.",
    nameEn: "Discover the best hotel in Miami Beach",
    descriptionEs: "¿Te has preguntado alguna vez cuál es el mejor hotel de Miami Beach? Esta soleada región de Florida es un verdadero imán para turistas de todo el mundo, ofreciendo vibrantes actividades nocturnas y relajantes paseos por sus icónicas playas de arena blanca.",
    descriptionEn: "Have you ever wondered which is the best hotel in Miami Beach? This sunny region of Florida is a true magnet for tourists from all over the world, offering vibrant nightlife and relaxing strolls along its iconic white sand beaches.",
    codeName: "the-best-hotel-miami",
    image: imgMiami,
    date: "06/05/2024",
    description: "description",
    type: ["pool"],
  },
  {
    lang: "es",
    name: "KnowsPuertoVallarta",
    nameEs: "Conoce cuál es el mejor hotel de Puerto Vallarta",
    nameEn: "Discover the best hotel in Puerto Vallarta",
    descriptionEs: "Muchas veces podemos preguntarnos cuál es el mejor hotel de Puerto Vallarta sobre todo si deseamos explorar uno de los destinos más encantadores y soleados de México.",
    descriptionEn: "We often wonder which is the best hotel in Puerto Vallarta, especially if we want to explore one of Mexico's most charming and sunny destinations.",
    codeName: "the-best-hotel-puerto-vallarta",
    image: imgVallarta,
    date: "06/05/2024",
    description: "description",
    type: ["beach"],
  },
  {
    lang: "es",
    name: "KnowsTampico",
    nameEs: "Conoce cuál es el mejor hotel de Tampico",
    nameEn: "Discover the best hotel in Tampico",
    descriptionEs: "Cuando piensas en visitar la hermosa ciudad de Tamaulipas, famosa por sus bellas playas y su rica herencia cultural,encontrar y quedarse en el mejor hotel de Tampico puede transformar una simple escapada en una experiencia inolvidable.",
    descriptionEn: "When you think about visiting the beautiful city of Tamaulipas, famous for its stunning beaches and rich cultural heritage, finding and staying at the best hotel in Tampico can transform a simple getaway into an unforgettable experience.",
    codeName: "the-best-hotel-tampico",
    image: imgTampico,
    date: "06/05/2024",
    description: "description",
    type: ["beach"],
  },
  {
    lang: "es",
    name: "KnowsCancun",
    nameEs: "Conoce cuál es el mejor hotel en Cancún",
    nameEn: "Discover the best hotel in Cancún",
    descriptionEs: "Si alguna vez te has preguntado cuál es el mejor hotel de Cancún, estás en el lugar indicado para encontrar respuestas. Este lugar, considerado como la joya del Caribe mexicano es famosa por su clima cálido, sus aguas cristalinas y sus impresionantes playas de arena blanca.",
    descriptionEn: "If you have ever wondered which is the best hotel in Cancún, you are in the right place to find answers. This location, considered the jewel of the Mexican Caribbean, is famous for its warm climate, crystal-clear waters, and stunning white sand beaches.",
    codeName: "the-best-hotel-cancun",
    image: imgCancun,
    date: "06/05/2024",
    description: "description",
    type: ["hotel", "cancun"],
  },
  {
    lang: "es",
    name: "KnowsCayoCuba",
    nameEs: "Conoce cuál es el mejor hotel en Cayo Santa María,",
    nameEn: "Discover the best hotel in Cayo Santa María, Cuba",
    descriptionEs: "¿Estás pensando visitar en tus vacaciones las paradisíacas playas de Cuba? En ese caso, definitivamente tienes que descansar en el mejor hotel en Cayo Santa María para disfrutar una experiencia inolvidable.",
    descriptionEn: "Are you thinking of visiting the paradisiacal beaches of Cuba for your vacation? In that case, you must definitely stay at the best hotel in Cayo Santa María to enjoy an unforgettable experience.",
    codeName: "the-best-hotel-cayo",
    image: imgCayo,
    date: "06/05/2024",
    description: "description",
    type: ["beach"],
  },
  {
    lang: "es",
    name: "KnowsIxtapa",
    nameEs: "Conoce cuál es el mejor hotel en Ixtapa para niños",
    nameEn: "Discover the best hotel in Ixtapa for kids",
    descriptionEs: "Cuando pensamos en unas vacaciones para toda la familia obviamente consideramos salir de la rutina y visitar las costas mexicanas. Y uno de los mejores destinos en las playas de México es Ixtapa.",
    descriptionEn: "When we think of a vacation for the whole family, we naturally consider getting away from the routine and visiting the Mexican coasts. And one of the best destinations on Mexico’s beaches is Ixtapa.",
    codeName: "the-best-hotel-ixtapa",
    image: imgIxtapa,
    date: "06/05/2024",
    description: "description",
    type: ["pool"],
  },
  {
    lang: "es",
    name: "KnowsMerida",
    nameEs: "Conoce cuál es el mejor hotel en Mérida Yucatán",
    nameEn: "Discover the best hotel in Mérida Yucatán",
    descriptionEs: "Si te preguntas cuál es el mejor hotel del mundo en Mérida Yucatán, la respuesta podría sorprenderte con la magnificencia y el encanto del Fiesta Americana Mérida. Esta joya de hotel se encuentra en una de las ciudades más encantadoras y ricas en cultura de todo México.",
    descriptionEn: "If you are wondering which is the best hotel in Mérida Yucatán, the answer might surprise you with the magnificence and charm of Fiesta Americana Mérida. This hotel gem is located in one of Mexico’s most charming and culturally rich cities.",
    codeName: "the-best-hotel-merida",
    image: imgMerida,
    date: "06/05/2024",
    description: "description",
    type: ["pool"],
  },
  {
    lang: "es",
    name: "KnowsMelia",
    nameEs: "Conoce cuál es el mejor hotel Meliá en Punta Cana",
    nameEn: "Discover the best Meliá hotel in Punta Cana",
    descriptionEs: "Cuando se trata de disfrutar de unas vacaciones de ensueño en el Caribe, elegir el mejor hotel Meliá en Punta Cana es una decisión crucial para que te asegures de vivir una experiencia inolvidable.",
    descriptionEn: "When it comes to enjoying a dream vacation in the Caribbean, choosing the best Meliá hotel in Punta Cana is a crucial decision to ensure you have an unforgettable experience.",
    codeName: "the-best-hotel-melia",
    image: imgMelia,
    date: "06/05/2024",
    description: "description",
    type: ["pool"],
  },
  {
    lang: "es",
    name: "DiscoverAcapulco",
    nameEs: "Descubre cuál es el mejor hotel de Acapulco",
    nameEn: "Discover the best hotel in Acapulco",
    descriptionEs: "Al planificar un viaje al estado de Guerrero es normal preguntarse lo siguiente: El mejor hotel de Acapulco, ¿cuál es? Sobre todo porque la elección del alojamiento en esta vibrante ciudad puede definir toda la experiencia de tus vacaciones.",
    descriptionEn: "When planning a trip to the state of Guerrero, it's normal to wonder: What is the best hotel in Acapulco? Especially because choosing the right accommodation in this vibrant city can define your entire vacation experience.",
    codeName: "the-best-hotel-acapulco",
    image: imgAcapulco,
    date: "06/05/2024",
    description: "description",
    type: ["pool"],
  },
  {
    lang: "es",
    name: "DiscoverCancun",
    nameEs: "Descubre cuál es el mejor hotel de Cancún para niños",
    nameEn: "Discover the best hotel in Cancún for kids",
    descriptionEs: "Acompáñanos a descubrir el alojamiento ideal para que pases unas vacaciones inolvidables junto a los más pequeños.",
    descriptionEn: "Join us to discover the ideal accommodation for an unforgettable vacation with your little ones.",
    codeName: "the-best-hotel-cancun-kids",
    image: imgDiscoverCancun,
    date: "06/05/2024",
    description: "description",
    type: ["pool", "cancun"],
  },
  {
    lang: "es",
    name: "DiscoverRivieraMaya",
    nameEs: "Descubre cuál es el mejor hotel de la Riviera Maya",
    nameEn: "Discover the best hotel in the Riviera Maya",
    descriptionEs: "Es posible que no sepas cuál es el mejor hotel de la Ciudad de México, y sin duda estarás encantado de explorar la capital de un país donde el hospedaje va más allá de simplemente ofrecer un lugar para dormir.",
    descriptionEn: "Located in the state of Quintana Roo, Mexico, the Riviera Maya is a tourist corridor stretching along impressive beaches bathed by the Caribbean Sea. With its rich Mayan culture, magnificent cenotes, and vibrant marine life, it’s a destination that attracts visitors from all over the world.",
    codeName: "the-best-hotel-riviera-maya",
    image: imgRiviera,
    date: "06/05/2024",
    description: "description",
    type: ["beach"],
  },
  {
    lang: "es",
    name: "DiscoverMexico",
    nameEs: "Descubre cuál es el mejor hotel de México",
    nameEn: "Discover the best hotel in Mexico City",
    descriptionEs: "Seguro cuando te preguntas ¿cuál es el mejor hotel en Nuevo Vallarta?, inmediatamente te imaginas un lugar de ensueño, donde la arena blanca, las aguas azul turquesa y un impecable servicio al cliente son cosas del día a día.",
    descriptionEn: "You may not know which is the best hotel in Mexico City, and you will undoubtedly be delighted to explore the capital of a country where hospitality goes beyond simply offering a place to sleep.",
    codeName: "the-best-hotel-mexico",
    image: imgMexico,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "DiscoverNuevoVallarta",
    nameEs: "Descubre cuál es el mejor hotel de Nuevo Vallarta",
    nameEn: "Discover the best hotel in Nuevo Vallarta",
    descriptionEs:
      "Seguro cuando te preguntas ¿cuál es el mejor hotel en Nuevo Vallarta?, inmediatamente te imaginas un lugar de ensueño, donde la arena blanca, las aguas azul turquesa y un impecable servicio al cliente son cosas del día a día.",
    descriptionEn: "Surely when you wonder what the best hotel in Nuevo Vallarta is, you immediately imagine a dream place, where white sand, turquoise blue waters, and impeccable customer service are daily experiences.",
    codeName: "the-best-hotel-nuevo-vallarta",
    image: imgNuevoVallarta,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "DiscoverDisney",
    nameEs: "Descubre cuál es el mejor hotel dentro de Disney Orlando",
    nameEn: "Discover the Best Hotel in Disney Orlando",
    descriptionEs:
      "Cuando piensas en visitar el mágico mundo de Disney en Orlando, una de las primeras cosas que probablemente te viene a la mente, además de los emocionantes parques temáticos y los personajes icónicos, es dónde te hospedarás durante tu fantástica aventura.",
    descriptionEn: "When you think about visiting the magical world of Disney in Orlando, one of the first things that probably comes to mind, aside from the exciting theme parks and iconic characters, is where you'll stay during your fantastic adventure.",
    codeName: "the-best-hotel-disney",
    image: imgDisney,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
  {
    lang: "es",
    name: "DiscoverCuernavaca",
    nameEs: "Descubre cuál es el mejor hotel en Cuernavaca",
    nameEn: "Discover the Best Hotel in Cuernavaca",
    descriptionEs: "Si deseas encontrar, el mejor hotel en Cuernavaca, puede que existan varias opciones que capten tu atención. Sin embargo, un establecimiento destaca por encima de los demás por su exquisita combinación de lujo, historia y servicio personalizado: el Anticavilla Restaurant, Hotel & Spa.",
    descriptionEn: "If you're looking for the best hotel in Cuernavaca, you may find several options that catch your attention. However, one establishment stands out above the rest for its exquisite combination of luxury, history, and personalized service: the Anticavilla Restaurant, Hotel & Spa.",
    codeName: "the-best-hotel-cuernavaca",
    image: imgCuernavaca,
    date: "06/05/2024",
    description: "description",
    type: ["pool"],
  },
  {
    lang: "es",
    name: "DiscoverGuayabitos",
    nameEs: "Descubre cuál es el mejor hotel en Guayabitos",
    nameEn: "Discover the Best Hotel in Guayabitos",
    descriptionEs: "¿Cuál es el mejor hotel todo incluido en Guayabitos?Esta es una pregunta que muchos viajeros se hacen al planificar unas vacaciones en el encantador Rincón de Guayabitos en Nayarit, México.",
    descriptionEn: "What is the best all-inclusive hotel in Guayabitos? This is a question many travelers ask when planning a vacation in the charming Rincón de Guayabitos in Nayarit, Mexico.",
    codeName: "the-best-hotel-guayabitos",
    image: imgGuayabitos,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "DiscoverHabana",
    nameEs: "Descubre cuál es el mejor hotel en La Habana, Cuba",
    nameEn: "Discover the Best Hotel in Havana, Cuba",
    descriptionEs: "Cuál es el mejor hotel moderno en La Habana, Cuba? Si esta pregunta ronda tu mente mientras planeas una escapada a la vibrante capital cubana, has llegado al artículo indicado.",
    descriptionEn: "What is the best modern hotel in Havana, Cuba? If this question is on your mind while planning a getaway to the vibrant Cuban capital, you’ve come to the right article.",
    codeName: "the-best-hotel-habana",
    image: imgHabana,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "DiscoverGrutasTolantongo",
    nameEs: "Descubre cuál es el mejor hotel en las Grutas de Tolantongo",
    nameEn: "Discover the Best Hotel in the Tolantongo Caves",
    descriptionEs: "El hospedaje en Tolantongo, Hidalgo, es una experiencia inolvidable si estás buscando relajación en un entorno natural excepcional. Déjame decirte que esta región es famosa por sus aguas termales y su paisaje impresionante, pero si deseas disfrutar plenamente de esta maravilla natural, es fundamental elegir el lugar adecuado para hospedarte.",
    descriptionEn: "Staying in Tolantongo, Hidalgo, is an unforgettable experience if you're looking for relaxation in an exceptional natural setting. Let me tell you, this region is famous for its hot springs and stunning landscapes, but if you want to fully enjoy this natural wonder, it's crucial to choose the right place to stay.",
    codeName: "the-best-hotel-tolantongo",
    image: imgTolantongo,
    date: "06/05/2024",
    description: "description",
    type: ["pool"],
  },
  {
    lang: "es",
    name: "DiscoverLosCabosSanLucas",
    nameEs: "Descubre cuál es el mejor hotel en Los Cabos San Lucas",
    nameEn: "Discover the Best Hotel in Los Cabos San Lucas",
    descriptionEs: "Es normal que te preguntes cuál es el mejor hotel de Los Cabos San Lucas si es que buscas combinar lujo y exclusividad en un destino que además cuenta con bellezas naturales en un ambiente sofisticado y relajado.",
    descriptionEn: "It's normal to wonder what the best hotel in Los Cabos San Lucas is if you're looking to combine luxury and exclusivity in a destination that also offers natural beauty in a sophisticated and relaxed setting.",
    codeName: "the-best-hotel-los-cabos-san-lucas",
    image: imgCabos,
    date: "06/05/2024",
    description: "description",
    type: ["pool"],
  },
  {
    lang: "es",
    name: "DiscoverMahahual",
    nameEs: "Descubre cuál es el mejor hotel en Mahahual",
    nameEn: "Discover the Best Hotel in Mahahual",
    descriptionEs: "Si buscas darte un escape por el caribe mexicano podrías visitar uno de los muchos puntos famosos en las costas de la Península de Yucatán, tal como Mahahual, Holbox o Isla Mujeres.",
    descriptionEn: "If you're looking to escape to the Mexican Caribbean, you could visit one of the many famous spots on the Yucatan Peninsula’s coast, such as Mahahual, Holbox, or Isla Mujeres.",
    codeName: "the-best-hotel-mahahual",
    image: imgMahahual,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
  {
    lang: "es",
    name: "DiscoverNewYork",
    nameEs: "Descubre cuál es el mejor hotel en New York",
    nameEn: "Discover the Best Hotel in New York",
    descriptionEs: "Si ya planeas visitar la vibrante ciudad que nunca duerme probablemente. ¿Cuál es el mejor hotel para quedarse en New York? Es una pregunta que seguro ha pasado por tu cabeza.",
    descriptionEn: "If you're already planning to visit the vibrant city that never sleeps, you might wonder: what is the best hotel to stay in New York? This is a question that has probably crossed your mind.",
    codeName: "the-best-hotel-new-york",
    image: imgNewYork,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "DiscoverHotelRiu",
    nameEs: "Descubre cuál es el mejor hotel Riu en Cancún",
    nameEn: "Discover the Best Riu Hotel in Cancun",
    descriptionEs: "Cuando nos preguntamos ¿Cuántos hoteles Riu hay en Cancún? Tenemos que tener en cuenta que encontrarás más de una opción para ti, ya que los hoteles disponibles de Riu en Cancún son 7: Hotel Riu Caribe, Hotel Riu Dunamar, Hotel Riu Palace Las Americas, Hotel Riu Palace Peninsula, Hotel Riu Latino, Hotel Riu Palace Costa Mujeres y el Hotel Riu Cancun.",
    descriptionEn: "When we ask ourselves how many Riu hotels there are in Cancun, we have to keep in mind that you’ll find more than one option for you, as there are 7 available Riu hotels in Cancun: Hotel Riu Caribe, Hotel Riu Dunamar, Hotel Riu Palace Las Americas, Hotel Riu Palace Peninsula, Hotel Riu Latino, Hotel Riu Palace Costa Mujeres, and Hotel Riu Cancun.",
    codeName: "the-best-hotel-riu-cancun",
    image: imgRiuCancun,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "ExtenDiscoverAkumal",
    nameEs: "Descubre Akumal: El paraíso secreto de la Riviera Maya",
    nameEn: "Discover Akumal: The Secret Paradise of the Riviera Maya",
    descriptionEs: "En la vasta y vibrante geografía mexicana se encuentra el mágico Caribe. Aquí encontrarás tiernas costas de arena blanca que esconden un rincón pacífico que invita a ser descubierto: Akumal.",
    descriptionEn: "In the vast and vibrant Mexican geography, you’ll find the magical Caribbean. Here you’ll find gentle white sand beaches hiding a peaceful corner waiting to be discovered: Akumal.",
    codeName: "discovering-akumal",
    image: imgExtenAkumal,
    date: "06/05/2024",
    description: "description",
    type: ["beach"],
  },
  {
    lang: "es",
    name: "ExtenDiscoverChihuahua",
    nameEs: "Descubre las maravillas de Barrancas del Cobre en Chihuahua",
    nameEn: "Discover the Wonders of Copper Canyon in Chihuahua",
    descriptionEs: "¡Hola, aventurero! Si estás buscando un destino que combine paisajes impresionantes con una dosis de adrenalina y cultura, entonces debes poner considerar las Barrancas del Cobre en tu radar.",
    descriptionEn: "Hello, adventurer! If you’re looking for a destination that combines breathtaking landscapes with a dose of adrenaline and culture, then you should put Copper Canyon on your radar.",
    codeName: "discovering-chihuahua",
    image: imgExtendChihuahua,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
  {
    lang: "es",
    name: "FindCampeche",
    nameEs: "Descubriendo Campeche: Un tesoro oculto de la cultura y colores de México",
    nameEn: "Discovering Campeche: A Hidden Treasure of Culture and Colors in Mexico",
    descriptionEs: "¿Deseas embarcarte en una experiencia mágica? Puedes encontrarla en Campeche, uno de los estados más fascinantes y coloridos de México que aún no es tan popular, por lo que podrás visitarlo con la tranquilidad de que no te enfrentarás al típico bullicio de localidades famosas.",
    descriptionEn: "Do you want to embark on a magical experience? You can find it in Campeche, one of the most fascinating and colorful states in Mexico that is not yet very popular, so you can visit with the peace of mind that you won't face the typical crowds of famous locations.",
    codeName: "discovering-campeche",
    image: imgExtenCampeche,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
  {
    lang: "es",
    name: "ExtenKnowsChetumal",
    nameEs: "Conoce la majestuosidad de Chetumal en esta guía para viajeros",
    nameEn: "Discover the Majesty of Chetumal in this Travel Guide",
    descriptionEs: "¿Te has preguntado alguna vez qué secretos guarda el sur de México? Hoy te llevo a descubrir Chetumal, una ciudad que no solo es la capital del estado de Quintana Roo sino también un portal hacia increíbles aventuras en la Grand Costa Maya.",
    descriptionEn: "Have you ever wondered what secrets the south of Mexico holds? Today, I take you to discover Chetumal, a city that is not only the capital of Quintana Roo but also a gateway to incredible adventures in the Grand Costa Maya.",
    codeName: "know-chetumal",
    image: imgExtenChetumal,
    date: "06/05/2024",
    description: "description",
    type: ["beach"],
  },
  {
    lang: "es",
    name: "ExtenBarraDeNavidad",
    nameEs: "Barra de Navidad: Un paraíso costero en el corazón de México",
    nameEn: "Barra de Navidad: A Coastal Paradise in the Heart of Mexico",
    descriptionEs: "Acompáñenme a descubrir por qué Barra de Navidad debe estar en tu lista de próximos destinos para visitar.",
    descriptionEn: "Join me to discover why Barra de Navidad should be on your list of upcoming destinations to visit.",
    codeName: "barra-de-navidad",
    image: imgExtenNavidad,
    date: "06/05/2024",
    description: "description",
    type: ["beach"],
  },
  {
    lang: "es",
    name: "ExtenChiapasMagic",
    nameEs: "Chiapas Mágico: Un viaje por el corazón cultural y natural de México",
    nameEn: "Magical Chiapas: A Journey Through the Cultural and Natural Heart of Mexico",
    descriptionEs: "Aquí conocerás lo que necesitas saber de Chiapas, desde la importante información de Chiapas hasta espectaculares atracciones en Chiapas, México",
    descriptionEn: "Here you will learn everything you need to know about Chiapas, from essential information to the spectacular attractions in Chiapas, Mexico.",
    codeName: "chiapas-magic",
    image: imgExtenChiapas,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
  {
    lang: "es",
    name: "DiscoverNuevoVallartaAi",
    nameEs: "Descubre cuál es el mejor hotel todo incluido en Nuevo Vallarta",
    nameEn: "Discover the Best All-Inclusive Hotel in Nuevo Vallarta",
    descriptionEs: "Quizá necesitas conocer cuál es el mejor hotel de Nuevo Vallarta, pues muchos te habrán comentado acerca de este paraíso que destaca por sus impresionantes playas de arena dorada y sus aguas cristalinas, además de su exuberante vegetación y la calidez de su gente, por este motivo te recomendamos hospedarte en un hotel excelente.",
    descriptionEn: "You might want to know which is the best hotel in Nuevo Vallarta, as many may have told you about this paradise known for its stunning golden sandy beaches, crystal clear waters, lush vegetation, and warm hospitality. For this reason, we recommend staying at an excellent hotel.",
    codeName: "discovering-all-inclusive-nuevo-vallarta",
    image: imgAllInclusiveNuevoVallarta,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindAcapulcoZonaDorada",
    nameEs: "Encuentra cuál es el mejor hotel de Acapulco zona dorada",
    nameEn: "Find the Best Hotel in Acapulco's Golden Zone",
    descriptionEs: "Acapulco es uno de los destinos turísticos más emblemáticos de México, conocido por sus impresionantes paisajes, su vibrante vida nocturna y sus magníficas playas.",
    descriptionEn: "Acapulco is one of the most iconic tourist destinations in Mexico, known for its stunning landscapes, vibrant nightlife, and magnificent beaches.",
    codeName: "find-all-inclusive-acapulco-zona-dorada",
    image: imgAllInclusiveAcapulco,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindCancunAi",
    nameEs: "Encuentra cuál es el mejor hotel de Cancún todo incluido",
    nameEn: "Find the Best All-Inclusive Hotel in Cancun",
    descriptionEs: "Cuando te preguntas cuál es el mejor hotel de Cancún todo incluido, la conversación inevitablemente se dirige hacia cuál hotel te puede ofrecer experiencias de lujo y comodidad.",
    descriptionEn: "When you ask yourself which is the best all-inclusive hotel in Cancun, the conversation inevitably shifts to which hotel can offer you luxury and comfort experiences.",
    codeName: "find-all-inclusive-cancun",
    image: imgAllInclusiveCancun,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindTheBestHotelIxtapa",
    nameEs: "Encuentra cuál es el mejor hotel de Ixtapa",
    nameEn: "",
    descriptionEs: "Encuentra cuál es el mejor hotel de Ixtapa",
    descriptionEn: "Find the best hotel in Ixtapa",
    codeName: "find-all-inclusive-ixtapa",
    image: imgAllInclusiveIxtapa,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindBestHotelLasVegas",
    nameEs: "Encuentra cuál es el mejor hotel de Las Vegas",
    nameEn: "Find the Best Hotel in Las Vegas",
    descriptionEs: "Cuando pensamos en “los 10 mejores hoteles en Las Vegas”, rápidamente nos imaginamos un mundo de lujo, entretenimiento y deslumbrantes luces nocturnas.",
    descriptionEn: "When we think of 'the top 10 hotels in Las Vegas', we quickly imagine a world of luxury, entertainment, and dazzling nightlife.",
    codeName: "find-las-vegas",
    image: imgAllInclusiveLasVegas,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindBestHotelPuntaCanaAi",
    nameEs: "Encuentra cuál es el mejor hotel de Punta Cana all inclusive",
    nameEn: "Find the Best All-Inclusive Hotel in Punta Cana",
    descriptionEs: "Cuando pensamos en los mejores hoteles de Punta Cana es necesario elevar el estándar de hotel común y corriente a uno con instalaciones increíbles. Y si añadimos a la mezcla el concepto de 'all inclusive' sube aún más elestándar de lujo y comodidad que pocos lugares en el mundo pueden ofrecer.",
    descriptionEn: "When we think of the best hotels in Punta Cana, it's necessary to elevate the standard from an ordinary hotel to one with incredible facilities. And if we add the 'all-inclusive' concept to the mix, it raises the standard of luxury and comfort that few places in the world can offer.",
    codeName: "find-punta-cana",
    image: imgAllInclusivePuntaCana,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindHolbox",
    nameEs: "Encuentra cuál es el mejor hotel en Holbox",
    nameEn: "Find the Best Hotel in Holbox",
    descriptionEs: "Ven y descubre el mejor hotel en Holbox; esta es una hermosa isla situada al norte de la Península de Yucatán, en México. Y en esteartículo te recomendaremos una serie de aspectos esenciales al momentode hospedarse.",
    descriptionEn: "Come and discover the best hotel in Holbox; this is a beautiful island located north of the Yucatan Peninsula in Mexico. In this article, we will recommend a series of essential aspects when choosing accommodation.",
    codeName: "find-the-best-holbox",
    image: imgFindHolbox,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindPuertoEscondido",
    nameEs: "Encuentra cuál es el mejor hotel en Puerto Escondido",
    nameEn: "Find the Best Hotel in Puerto Escondido",
    descriptionEs: "Si estás buscando el mejor hotel en Puerto Escondido, definitivamente necesitamos hablar de una joya oculta a lo largo de la costa oaxaqueña de México que te hará dejar de explorar opciones.",
    descriptionEn: "If you are looking for the best hotel in Puerto Escondido, we definitely need to talk about a hidden gem along the Oaxacan coast of Mexico that will make you stop exploring other options.",
    codeName: "find-puerto-escondido",
    image: imgFindPuertoEscondido,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindCancunFamily",
    nameEs: "Encuentra cuál es el mejor hotel familiar en Cancún",
    nameEn: "Find the Best Family Hotel in Cancun",
    descriptionEs: "Si lo que buscas en tener unas vacaciones familiares en las playas más hermosas de México probablemente lo primero que quieres saber es cuál es El mejor hotel familiar en Cancún.",
    descriptionEn: "If you're looking for a family vacation on Mexico's most beautiful beaches, probably the first thing you want to know is which is the best family hotel in Cancun.",
    codeName: "find-cancun-hotel-family",
    image: imgFindCancunFamily,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindPuertoVallarta",
    nameEs: "Encuentra cuál es el mejor hotel todo incluido en Puerto Vallarta",
    nameEn: "Find the Best All-Inclusive Hotel in Puerto Vallarta",
    descriptionEs: "¿Planeando una escapada tropical a las bellas costas de México? Si buscas visitar Puerto Vallarta, relajación completa, excelente servicio al cliente y una experiencia inolvidable, elegir un hotel todo incluido en Puerto Vallarta podría ser tu mejor opción.",
    descriptionEn: "Planning a tropical getaway to Mexico's beautiful coasts? If you're looking to visit Puerto Vallarta for complete relaxation, excellent customer service, and an unforgettable experience, choosing an all-inclusive hotel in Puerto Vallarta might be your best option.",
    codeName: "find-puerto-vallarta",
    image: imgFindPuertoVallarta,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "FindVaraderoCuba",
    nameEs: "Encuentra cuál es el mejor hotel todo incluido en Varadero, Cuba",
    nameEn: "Find the Best All-Inclusive Hotel in Varadero, Cuba",
    descriptionEs: "Si buscas una escapada tropical que combine lujo, placer y belleza natural, Varadero, Cuba destino que no te puedes perder. Y si quieres descansar en este paraíso, obviamente necesitas saber cuál es el mejor hotel en Varadero, Cuba",
    descriptionEn: "If you're looking for a tropical getaway that combines luxury, pleasure, and natural beauty, Varadero, Cuba is a destination you can't miss. And if you want to relax in this paradise, you obviously need to know which is the best hotel in Varadero, Cuba.",
    codeName: "find-varadero-cuba",
    image: imgFindVaraderoCuba,
    date: "06/05/2024",
    description: "description",
    type: ["hotel"],
  },
  {
    lang: "es",
    name: "Findbacalar",
    nameEs: "Bacalar, un paraíso escondido en la Riviera Maya",
    nameEn: "Bacalar: A Hidden Paradise in the Riviera Maya",
    descriptionEs: "Si buscas un escape del bullicio cotidiano y un contacto genuino con la naturaleza, Bacalar, Quintana Roo es tu destino ideal. En este artículo, te invitamos a adentrarte en los encantos de Bacalar y descubrir por qué deberías añadirlo a tu lista de próximos viajes.",
    descriptionEn: "If you're seeking an escape from the daily hustle and a genuine connection with nature, Bacalar, Quintana Roo is your ideal destination. In this article, we invite you to dive into the charms of Bacalar and discover why you should add it to your travel list.",
    codeName: "bacalar-riviera-maya",
    image: imgExtenBacalar,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
  {
    lang: "es",
    name: "FindCatemaco",
    nameEs: "Guía completa para viajar a la enigmática ciudad de Catemaco",
    nameEn: "Complete Guide to Traveling to the Enigmatic City of Catemaco",
    descriptionEs: "Si estás listo para una aventura fuera de lo común, sigue leyendo y descubre todo lo que necesitas saber para explorar esta fascinante ciudad.",
    descriptionEn: "If you're ready for an out-of-the-ordinary adventure, keep reading and discover everything you need to know to explore this fascinating city.",
    codeName: "guide-catemaco-veracruz",
    image: imgExtenGuideCatemaco,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
  {
    lang: "es",
    name: "FindCancun",
    nameEs: "Secretos de Cancún: Tu guía esencial para vivir una experiencia inolvidable",
    nameEn: "Secrets of Cancun: Your Essential Guide for an Unforgettable Experience",
    descriptionEs: "¿Alguna vez has soñado con escaparte a un paraíso de aguas turquesa y arenas blancas? Pues Cancún, Quintana Roo, México, es el lugar que estás buscando. ",
    descriptionEn: "Have you ever dreamed of escaping to a paradise of turquoise waters and white sands? Well, Cancun, Quintana Roo, Mexico, is the place you’re looking for.",
    codeName: "secrets-cancun",
    image: imgExtenSecretsCancun,
    date: "06/05/2024",
    description: "description",
    type: ["cancun", "beach"],
  },
  {
    lang: "es",
    name: "ExtenAguascalientes",
    nameEs: "Todo lo que debes saber si viajas a la hermosa ciudad de Aguascalientes",
    nameEn: "Everything You Need to Know When Traveling to the Beautiful City of Aguascalientes",
    descriptionEs: "Bienvenidos a una de las ciudades más icónicas de México, donde la tradición se fusiona con la modernidad y los paisajes naturales. Precisamente por eso Aguascalientes, más que un destino, es una experiencia vibrante que espera tu visita. ",
    descriptionEn: "Welcome to one of Mexico's most iconic cities, where tradition blends with modernity and natural landscapes. For that reason, Aguascalientes is more than just a destination; it's a vibrant experience waiting for your visit.",
    codeName: "everything-you-need-to-know-aguascalientes",
    image: imgExtenAguascalientes,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
  {
    lang: "es",
    name: "ExtenComeAcapulco",
    nameEs: "Ven a conocer Acapulco en todo su esplendor",
    nameEn: "Come and Discover Acapulco in All Its Splendor",
    descriptionEs: "Acapulco, ciudad ubicada en el estado de Guerrero en la costa del Pacífico mexicano, es uno de esos destinos que parecen haber sido creados por la naturaleza para el deleite humano.",
    descriptionEn: "Acapulco, a city located in the state of Guerrero on the Mexican Pacific coast, is one of those destinations that seem to have been created by nature for human delight.",
    codeName: "come-and-see-acapulco",
    image: imgExtenComeAcapulco,
    date: "06/05/2024",
    description: "description",
    type: ["other"],
  },
];
